services:
  backend:
    container_name: moneyTracker-backend
    build:
      context: ./moneyTracker
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/moneyTracker
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      money-tracker-network:
        aliases:
          - backend

  frontend:
    container_name: moneyTracker-frontend
    build:
      context: ./moneyTracker-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
    ports:
      - "80:80"
    networks:
      money-tracker-network:
        aliases:
          - frontend

  db:
    image: postgres:latest
    restart: always
    container_name: moneyTracker-database
    env_file:
      - .env
    environment:
      POSTGRES_DB: moneyTracker
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      money-tracker-network:
        aliases:
          - database
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  money-tracker-network:
    driver: bridge

volumes:
  postgres-data: