services:
  db:
    image: postgres:latest
    container_name: moneytracker_database_container
    restart: always
    environment:
      - POSTGRES_DB=moneyTracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PASSWORD
    ports:
      - '5432:5432'
    networks:
      - money-tracker-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  backend:
    container_name: moneytracker_backend_container
    build: ./moneyTracker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/moneyTracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - money-tracker-network

  frontend:
    container_name: moneytracker_frontend_container
    build: ./moneyTracker-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    volumes:
      - frontend-volume:/var/www/html
    networks:
      - money-tracker-network

  nginx:
    container_name: nginx-container
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend-volume:/var/www/html
    depends_on:
      - backend
      - frontend
      - db

volumes:
  postgres-volume:
  frontend-volume:

networks:
  money-tracker-network:
    driver: bridge
