version: '3.8'

services:
  backend:
    container_name: moneyTracker-backend
    build:
      context: ./moneyTracker
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    ports:
      - "3001:3001"
    networks:
      money-tracker-network:
        aliases:
          - backend

  frontend:
    container_name: moneyTracker-frontend
    build:
      context: ./moneyTracker-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
    ports:
      - "3000:3000"
    networks:
      money-tracker-network:
        aliases:
          - frontend

  db:
    image: postgres:latest
    restart: always
    container_name: moneyTracker-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      money-tracker-network:
        aliases:
          - database
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  money-tracker-network:
    driver: bridge

volumes:
  postgres-data: