services:
  backend:
    container_name: moneyTracker-back
    build:
      context: ./moneyTracker
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - money-tracker-network

  frontend:
    container_name: moneyTracker-front
    build:
      context: ./moneyTracker-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "80:80"
    networks:
      - money-tracker-network

  db:
    image: postgres:latest
    container_name: moneyTracker-database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: moneyTracker
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - money-tracker-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external: false
networks:
  money-tracker-network:
    driver: bridge
