services:

  db:
    image: postgres:latest
    container_name: moneytracker_database_container
    restart: always
    environment:
      - POSTGRES_DB=moneyTracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PASSWORD
    ports:
      - '5432:5432'
    networks:
      - money-tracker-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: moneytracker_backend_container
    build:
      context: ./moneyTracker
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/moneyTracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"
    networks:
      - money-tracker-network

  frontend:
    container_name: moneytracker_frontend_container
    build:
      context: ./moneyTracker-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
    ports:
      - "80:80"
    networks:
      - money-tracker-network


volumes:
  postgres-data:
    external: false

networks:
  money-tracker-network:
    driver: bridge
